services:
  wordpress_bike:
    image: wordpress:latest
    volumes:
      - "./www:/var/www/html"
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      traefik:
        ipv4_address: 192.168.1.13
    restart: always
    working_dir: /var/www/html/bike
    environment:
      WORDPRESS_DB_HOST: 192.168.1.10:3306
      WORDPRESS_DB_NAME: wordpress_bike
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','https://${DOMAIN}/bike');
        define('WP_SITEURL','https://${DOMAIN}/bike');
    labels:
      - traefik.enable=true
      - traefik.http.routers.https.rule=Host(`${DOMAIN}`) && PathPrefix(`/bike/`)
      - traefik.http.routers.https.entrypoints=https
      - traefik.http.routers.https.tls=true
      - traefik.http.routers.https.tls.certresolver=${CERT_RESOLVER}
networks:
  traefik:
    external: true