services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./data:/var/lib/mysql"
      - "./init:/docker-entrypoint-initdb.d"
    restart: always
    ports:
      - 3306:3306
    networks:
      traefik:
        ipv4_address: 192.168.1.10
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
networks:
  traefik:
    external: true
